sudo: false
language: node_js
node_js:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 'stable'
  - 'lts/*'
install:
  - npm install -g yarn
  - yarn install
dist: trusty
sudo: false
cache: yarn
script:
  - yarn run build
